flowchart LR
  subgraph Data_Engineer
    Ingest_Data_C4[Ingest_Data]
    Analyze_Data_C6[Analyze_Data]
    Preprocess_Data_C8[Preprocess_Data]
  end

  subgraph Model_Engineer
    Train_Model_C12[Train_Model]
    Tune_Model_C14[Tune_Model]
    Evaluate_and_Test_Model_C16[Evaluate_and_Test_Model]
    Register_Model_C18[Register_Model]
  end

  Ingest_Data_C4 --> Analyze_Data_C6 --> Preprocess_Data_C8 --> Train_Model_C12 --> Tune_Model_C14 --> Evaluate_and_Test_Model_C16 --> Register_Model_C18